icd_10_map = {'Cough': 'R05',
              'Chills': 'R68.83T',
              'Headache': 'R51',
              'Fatigue': 'R53.83',
              'Fever': 'R50.9',
              'Nasal congestion': 'R09.81',
              'Sore throat': 'R07.0',
              'Muscle pain (Myalgia)': 'M79.1',
              'Diarrhea': 'R19.7',
              'Loss of appetite': 'R63',
              'New loss of taste or smell': 'R43',
              'Recent Symptoms': 'Z20.822',
              'Recent Exposure': 'Z20.822',
              'Retest': 'U07.1',
              'Group setting': 'Z20.822',
              'Doctor Recommendation': 'Z20.822',
              'Tobacco': 'Z72.0',
              'Healthcare Worker': 'Z20.822',
              'Travel Consultation': 'Z71.84'}
